### ISSUE TITLE
如果选择“自动选择”没法勾选 跟随app启动退出吗？

### ISSUE THREAD

**Issue by fengmikaelson** [MxIris-LyricsX-Project/LyricsX#12]
![image](https://github.com/user-attachments/assets/4e7c7a18-e4a0-4fb2-aab7-b6b0de513073)
 
只能固定选择某个app才能拉起吗？

**Comment by Mx-Iris** [comment]
自动选择走的是系统now playing，没法知道你用的是什么播放器，所以跟踪不了
