### ISSUE TITLE
搜索特定歌曲时候软件会崩溃，1.7beta1

### ISSUE THREAD

**Issue by Nocti5-real** [MxIris-LyricsX-Project/LyricsX#13]
搜索周杰伦的发如雪时软件会崩溃，重新启动无法解决，百分百触发
MacBook Air M2 15inch，macOS14.3.1

1.6.7版本无此问题

**Comment by Mx-Iris** [comment]
用最新的beta版

**Comment by Nocti5-real** [comment]
> 用最新的beta版

已更新，感谢！
