### ISSUE TITLE
关于 brew 安装方式

### ISSUE THREAD

**Issue by edr1412** [MxIris-LyricsX-Project/LyricsX#16]
Readme中brew命令运行失败
第一行似乎extras有拼写错误
第二行也是无法运行

**Comment by Mx-Iris** [comment]
这个是某个好心人帮我加的，我没往brew传过软件，不知道咋弄，如果你有时间的话可以帮忙弄弄

**Comment by Corlius** [comment]
> 这个是某个好心人帮我加的，我没往brew传过软件，不知道咋弄，如果你有时间的话可以帮忙弄弄

正确的安装命令应该是：
```shell
brew tap brewforge/extras
brew install brewforge/extras/lyricsx-mxiris
```

**Comment by edr1412** [comment]
> > 这个是某个好心人帮我加的，我没往brew传过软件，不知道咋弄，如果你有时间的话可以帮忙弄弄
> 
> 正确的安装命令应该是：
> 
> ```shell
> brew tap brewforge/extras
> brew install brewforge/extras/lyricsx-mxiris
> ```

这个可以用
