### ISSUE TITLE
Lyrics in the menu bar are sometimes not fully displayed 菜单栏歌词有时显示不全

### ISSUE THREAD

**Issue by Dzsyang** [MxIris-LyricsX-Project/LyricsX#2]
- Version:：GitHub Version 1.6.4 (2351)
- MacOS: Sonoma 14.5 (23F79)

<img width="287" alt="image" src="https://github.com/user-attachments/assets/0101649e-9f55-4da8-b524-eb9b70091833">

这似乎是一个遗留的问题：https://github.com/ddddxxx/LyricsX/issues/455
请问是否能将这个试验功能从“在没有歌词的时候是显示原本的icon”改为“在没有歌词的时候是显示空白or不显示原本的icon”，
或是通过更改其他设置从而避免歌词被省略的情况。

Thank you!

**Comment by Dzsyang** [comment]
> * Version:：GitHub Version 1.6.4 (2351)
> * MacOS: Sonoma 14.5 (23F79)
> 
> <img alt="image" width="287" src="https://private-user-images.githubusercontent.com/116958472/351390818-0101649e-9f55-4da8-b524-eb9b70091833.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3NTA2NjEsIm5iZiI6MTcyMTc1MDM2MSwicGF0aCI6Ii8xMTY5NTg0NzIvMzUxMzkwODE4LTAxMDE2NDllLTlmNTUtNGRhOC1iNTI0LWViOWI3MDA5MTgzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyM1QxNTU5MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NzI2OTM0MmIzOTkwYTA0YmQ4YzI3NjNiMmZmYzY4NGM3ZDU3NDdiMzk1NjY0MWY1OGU4MzQ0MWFlNDQwNWIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pmv2Kr2RO5Twh83XtBadR3DsKVT2ovfKUxz4SXfp73E">
> 这似乎是一个遗留的问题：[ddddxxx#455](https://github.com/ddddxxx/LyricsX/issues/455) 请问是否能将这个试验功能从“在没有歌词的时候是显示原本的icon”改为“在没有歌词的时候是显示空白or不显示原本的icon”， 或是通过更改其他设置从而避免歌词被省略的情况。
> 
> Thank you!

或许可以通过改写文件[MenuBarLyricsController.swift](https://github.com/MxIris-Application-Forks/LyricsX/blob/master/LyricsX/Controller/MenuBarLyricsController.swift)里的一些函数解决这个问题。

**Comment by Mx-Iris** [comment]
我明天看看

**Comment by Mx-Iris** [comment]
有能稳定复现的歌曲吗，播放器是什么

**Comment by Dzsyang** [comment]
> 有能稳定复现的歌曲吗，播放器是什么

- Player: Apple Music

目前已知会出现此问题的有三种情况：
- 歌曲第一句歌词
- 歌曲无歌词间奏后的第一句歌词
- 从短歌词到长歌词（需要一定长度差距）

基本可以归结为icon在menu bar的长度变化大的时候就会发生。
而对于同一句歌词，通过正常播放到此句和手动从其他位置跳到此句显示也不同，同样会根据长度变化的多少决定有无省略号进行省略。

Example: 
Taylor Swift - Cruel Summer (Lyrics from 163)
<img width="591" alt="image" src="https://github.com/user-attachments/assets/85eb9f11-2cb6-44b8-9e15-82819e766478">
前两句一定会发生省略问题：
<img width="300" alt="image" src="https://github.com/user-attachments/assets/186e3a7f-987d-47d0-8ac7-691fba56a5fe">
<img width="284" alt="image" src="https://github.com/user-attachments/assets/734c1c57-f97d-4b8e-918c-2d8098214596">
而从第三句话跳回第二句话，就不会发生省略：
<img width="299" alt="image" src="https://github.com/user-attachments/assets/1f3f42f6-f8c7-4bf2-ae9c-9e44f679a157">
再从第二句话跳回第一句话，仍然发生省略：
<img width="267" alt="image" src="https://github.com/user-attachments/assets/7bbcc3de-496e-4fb8-ae91-6d33fe637add">

以上跳转过程通过直接点击Apple Music中的歌词进行。

**Comment by Mx-Iris** [comment]
行，晚上回去研究下

**Comment by Mx-Iris** [comment]
作者做了判断，如果当前这句歌词设置之后 statusitem会不可见的话，超出去被application menu遮挡住了，就不断用...来缩短歌词让status item长度刚刚好，但是图标不合并的模式并没有这个处理，按理说不合并也会出现这种情况，他判断的方法可能由于系统版本或者使用了bartender, ice, hidden 等第三方自定义状态栏的软件导致判断错误，我目前已经去掉这个处理，看看后面能不能搞个固定宽度，然后太长的歌词滚动显示。

**Comment by Mx-Iris** [comment]
试试v1.6.6版本

**Comment by Dzsyang** [comment]
> 试试v1.6.6版本

Wonderful!

v1.6.6问题解决了，感谢

对于合并图标这个功能，我建议干脆改成不显示图标，直接把图标改成固定或者可设置长度的nil留空

方便的话可以再加上超过留空长度的歌词滚动显示

**Comment by Mx-Iris** [comment]
我注意到有一些歌的歌词中间是空的会显示图标，图标和歌词反复横跳，我觉得歌曲暂停并且这时歌词是空的时候才显示图标怎么样？滚动显示的话需要自定义视图，目前用的系统控件直接赋值歌词就行了，这个可以弄但不会这么快。

**Comment by Dzsyang** [comment]
> 我注意到有一些歌的歌词中间是空的会显示图标，图标和歌词反复横跳，我觉得歌曲暂停并且这时歌词是空的时候才显示图标怎么样？滚动显示的话需要自定义视图，目前用的系统控件直接赋值歌词就行了，这个可以弄但不会这么快。

合理的，歌曲中图标和歌词不会闪就可以。滚动显示也不急，大部分歌词长度还是可控的。
