### ISSUE TITLE
Bug: 在 Sequoia 中，偶尔出现双语歌词部分显示不全问题

### ISSUE THREAD

**Issue by MeetinaXD** [MxIris-LyricsX-Project/LyricsX#20]
<img width="368" alt="image" src="https://github.com/user-attachments/assets/c42d4edb-9592-408c-b898-849258aca468">

错误效果如图所示。

软件版本：`v1.7 beta-6`
系统版本：`macOS 15.0`

**Comment by Ryan-the-hito** [comment]
我也是……很奇怪

**Comment by Ryan-the-hito** [comment]
强制只显示一行之后可以规避这个 bug。

**Comment by Mx-Iris** [comment]
我还没升上去，这两天有空看看，之前beta也有人提过

**Comment by Mx-Iris** [comment]
已修复，见v1.7.0正式版
