### ISSUE TITLE
希望增加可以隐藏菜单栏图标

### ISSUE THREAD

**Issue by 17670454524** [MxIris-LyricsX-Project/LyricsX#7]
在勾选了"合并菜单栏图标与歌词"选项后，部分歌曲有停顿的时候，会偶尔显示出软件图标，而后又显示歌词，有分裂感
希望增加选项，可以直接隐藏掉软件图标👍

https://github.com/user-attachments/assets/0b732054-9fb9-4acb-b08a-d88830266893

**Comment by Mx-Iris** [comment]
有人提过了，下个beta版解决

**Comment by Mx-Iris** [comment]
见v1.7 beta-5解决方案
