### ISSUE TITLE
[BUG] 不能抓取Q音双语歌词

### ISSUE THREAD

**Issue by zjns** [MxIris-LyricsX-Project/LyricsX#8]
例如这首，Rearview - Brenn!
这首Q音是有中英双语歌词的，但是LyricsX搜索歌词发现搜索出来的仅有英文歌词，实际显示的也是单英歌词
听歌软件：Spotify 系统：macOS Sonoma 14.5

**Comment by ProudBenzene** [comment]
同求，大大加油！(੭ु´･ω･`)੭ु⁾⁾

**Comment by zjns** [comment]
稍微看了下，原来的接口fcg_query_lyric_new.fcg是有翻译歌词的，只是没有卡拉OK模式进度信息，现在貌似换了歌词接口，有卡拉OK进度信息，但是没有翻译歌词了

**Comment by Mx-Iris** [comment]
@zjns 搞定了，待会发个版本看看

**Comment by Mx-Iris** [comment]
v1.7-beta4 已修复

**Comment by ProudBenzene** [comment]
> v1.7-beta4 已修复

效果太完美了！感谢大佬🥹🥹🥹
